### ISSUE TITLE
Icon request

### ISSUE THREAD

**Issue by Yakumo-Yukari** [yeyushengfan258/Reversal-icon-theme#1]
- [x] Multitasking View
- [x] Vscode

**multitasking view**
![multitasking-view](https://user-images.githubusercontent.com/12076232/71760461-1dce1180-2ef9-11ea-8c1a-4a2dbea60220.png)
**Vscode**
![Vscode](https://user-images.githubusercontent.com/12076232/76925799-97c94080-6915-11ea-85c3-09bf2dbf0038.png)

**Comment by yeyushengfan258** [comment]
Okay, I'll add

**Comment by Yakumo-Yukari** [comment]
> Okay, I'll add

Thank you

**Comment by FedeCuci** [comment]
Would be awesome to have an icon for obs studio, kazam, wireshark and bashtop as well!

**Comment by yeyushengfan258** [comment]
No problem.
