### ISSUE TITLE
Visual Studio Code Icon is rendering as Visual Studio

### ISSUE THREAD

**Issue by MM-coder** [yeyushengfan258/Reversal-icon-theme#11]
On my Latte Dock the Visual Studio Code icon is rendering as Visual Studio 

![image](https://user-images.githubusercontent.com/22800592/98481367-996fad80-21f1-11eb-872d-dabf7e768737.png)

The .desktop file does however indicate `visual-studio-code`

**Comment by yeyushengfan258** [comment]
What's wrong with that?

**Comment by MM-coder** [comment]
Visual Studio Code's Icon is Blue, Visual Studio's is Purple, you've switched them up :D

**Comment by yeyushengfan258** [comment]
I see. Thank you

**Comment by MM-coder** [comment]
Fixed in a9b2f00
