### ISSUE TITLE
Linux Mint Cinnamon doesn't see the theme

### ISSUE THREAD

**Issue by younyokel** [yeyushengfan258/Reversal-icon-theme#2]
Hello.

I tried to install this icon theme on Linux Mint Cinnamon 19.3 Tricia, but it does not seems like it can see it. I installed it on `/usr/share/icons`, as it should be: nothing displays in the built-in Themes app.

Does anybody has this too?

Thanks.

**Comment by yeyushengfan258** [comment]
I don't know where the problem is. now

**Comment by younyokel** [comment]
I tried that again and it worked. Sorry for false alarm!

**Comment by younyokel** [comment]
Could you please delete this issue?
