### ISSUE TITLE
Different icons

### ISSUE THREAD

**Issue by gusazevedo** [yeyushengfan258/Reversal-icon-theme#21]
The images from the repo and the real icons when I installed are not the same. PS: (I've used the "-a" to make make sure that I have installed all the icons alternatives.

Image from the repo 
![image](https://user-images.githubusercontent.com/26143209/125861913-41e6a421-7007-4ebd-88cf-a0b9571816d6.png)

Icons affter install
![image](https://user-images.githubusercontent.com/26143209/125862082-938eb639-d9db-44c0-937a-3bb64f959c0b.png)

**Comment by yeyushengfan258** [comment]
The icon is correct, because I recently modified the rounded corners of the shape, and I just haven't changed the picture.
