### ISSUE TITLE
Icon Request: Lunar Client

### ISSUE THREAD

**Issue by nilathedragon** [yeyushengfan258/Reversal-icon-theme#30]
Lunar Client is a popular modified version of Minecraft. Similar to the BadLion Client.
Due to the helpful addons made for popular servers, this client is often chosen over the default minecraft launcher.

Would be cool to have an icon for it as well :)

Here is a link to them: https://www.lunarclient.com/

**Comment by yeyushengfan258** [comment]
Okay, I will add it.

**Comment by nilathedragon** [comment]
Thank you very much!
