### ISSUE TITLE
Icon Request: Strawberry Music Player

### ISSUE THREAD

**Issue by Lamecarlate** [yeyushengfan258/Reversal-icon-theme#38]
Hello!

Could you add an icon for Strawberry?

Official page: https://www.strawberrymusicplayer.org/

There is already an icon in Numix-Circle, from which Reversal inherits, the name is simply "strawberry".

Thanks a lot!

**Comment by yeyushengfan258** [comment]
No problem.

**Comment by Lamecarlate** [comment]
Years later, I see it's completed, thanks!
