### ISSUE TITLE
Icon request: Telegram desktop and chromium

### ISSUE THREAD

**Issue by pradhanharshil** [yeyushengfan258/Reversal-icon-theme#5]
Can you please add chromium and telegram Desktop icons ?

**Comment by yeyushengfan258** [comment]
OK.

**Comment by pradhanharshil** [comment]
Thanks

**Comment by pradhanharshil** [comment]
![512px-Telegram_2019_Logo svg](https://user-images.githubusercontent.com/33359708/84144211-822b6900-aa75-11ea-8c75-1810bb9a3d88.png)


![500px-Chromium_11_Logo](https://user-images.githubusercontent.com/33359708/84144404-d0406c80-aa75-11ea-9918-e016f93a2e96.png)

![Virtualbox_logo](https://user-images.githubusercontent.com/33359708/84144754-712f2780-aa76-11ea-9406-773f284d022a.png)

Please add virtualbox too.
