### ISSUE TITLE
Icon Request: Text editor, Builder, KeePassXC, Discord, Extension manager

### ISSUE THREAD

**Issue by wroyca** [yeyushengfan258/Reversal-icon-theme#61]
Here's some inconsistency:
* Text editor
* Builder *— Inconsistent with normal and missing with nightly*
* KeePassXC *— Doesn't follows KeePassXC logo*
* Discord *— Doesn't follows Discord colorscheme*
* Extension manager

![Screenshot from 2022-08-05 12-21-05](https://user-images.githubusercontent.com/91024200/183119587-3e471635-87e8-4bc6-9bc6-9778e5228dfc.png)
![Screenshot from 2022-08-05 12-21-13](https://user-images.githubusercontent.com/91024200/183119589-84a61d58-e7a7-4bec-8a31-9c09fbad368e.png)

**Comment by yeyushengfan258** [comment]
Thanks, I will add.

**Comment by wroyca** [comment]
@yeyushengfan258 Here is my attempt, I am not quite satisfied because the color of discord is slightly shifted and the symbol of the messenger is not rounded as it should be, but :  

![discord](https://user-images.githubusercontent.com/91024200/184547785-96c788e9-27c7-4ba4-871b-36c2ae9333bb.svg)
![keepassxc](https://user-images.githubusercontent.com/91024200/184547786-2dbbe20b-7d63-4016-999a-247c57b0103c.svg)
![messengerfordesktop](https://user-images.githubusercontent.com/91024200/184547787-f5fd8ecf-24ea-4a9f-b016-5ae6ebadf531.svg)

**Comment by yeyushengfan258** [comment]
OK, I will revise.
