### ISSUE TITLE
Icon Request: Seafile

### ISSUE THREAD

**Issue by ChrTall** [yeyushengfan258/Reversal-icon-theme#62]
The only Icon that is missing for my personal setup is an Icon for the Seafile Sync Client. Would that be possible to add it?
Also do you use the Jetbrains Ides with the Jetbrains Toolbox by any chance?
The problem with the toolbox is that it always overrides the .desktop files in the home directory after opening it, which replaces my custom desktop files with your icons. I know this is a problem of the jetbrains toolbox, but maybe you have a suggestion how to avoid it.
Thanks for you effort, this is by far my fav icon theme. (Reversal Blue Dark)

**Comment by yeyushengfan258** [comment]
Thank you, I will add the icon, as for your problem, I may not be able to solve it temporarily.

**Comment by ChrTall** [comment]
Thanks a lot.
