### ISSUE TITLE
Icon Request: Joplin

### ISSUE THREAD

**Issue by skoglump** [yeyushengfan258/Reversal-icon-theme#70]
Homepage: https://joplinapp.org/

**Comment by yeyushengfan258** [comment]
no problem.

**Comment by skoglump** [comment]
Thanks. I see now however that there is one already in `src/apps/scalable/joplin.svg`. It was not referenced correctly from the Joplin installation I have though, I have it installed through AUR (https://aur.archlinux.org/packages/joplin-appimage) and it seems that it expects the icon name to be `@joplinapp-desktop.svg`.

I fixed it locally by adding the following symlink:
`links/apps/scalable/@joplinapp-desktop.svg -> joplin.svg`

Sorry for the inconvenience.
