### ISSUE TITLE
Shop icon pixelated

### ISSUE THREAD

**Issue by mmintel** [yeyushengfan258/Reversal-icon-theme#8]
Hi there!

I am a newbie on linux. I am using Latte Dock and I saw that the "Shop" icon is pixelated where as the "update" icon is not. Can I change this somehow or do you have to adjust it in the icon pack? I am on a 4k display.
![Screenshot_20200829_120435](https://user-images.githubusercontent.com/4574612/91632141-2b339100-e9df-11ea-80c2-f274fb5953da.png)
![Screenshot_20200829_120443](https://user-images.githubusercontent.com/4574612/91632156-40102480-e9df-11ea-9623-51fcef980a07.png)

**Comment by yeyushengfan258** [comment]
This was the Dock's display problem because I made all the ICONS the same way.

**Comment by mmintel** [comment]
alright thanks for helping!
