### ISSUE TITLE
Cannot change folder color [NixOS/Gnome]

### ISSUE THREAD

**Issue by eureka-cpu** [yeyushengfan258/Reversal-icon-theme#85]
It seems that the actual `.svg` files are there but I can't seem to figure out how to change the color.

**Comment by yeyushengfan258** [comment]
src/apps

**Comment by eureka-cpu** [comment]
I'm not sure I understand. The apps folder seems to only have the icons for apps. I just want to change the color of the folders to blue, but since I'm using NixOS I can't run the install script.

**Comment by yeyushengfan258** [comment]
src/places/48   
The files can be modified, modified and re-installed on the line. There is a blue folder in the installation package.

**Comment by eureka-cpu** [comment]
It says that the links are broken?

![Screenshot from 2023-03-09 13-22-39](https://user-images.githubusercontent.com/57543709/224132417-796f3b49-6844-4f4d-9d66-716ad30931ee.png)

**Comment by eureka-cpu** [comment]
Ah I see what you meant now, I should just download the blue folder variant. This one is just default.
