### ISSUE TITLE
[Icon Request] QQ, QQmusic and WPS icons

### ISSUE THREAD

**Issue by neovali** [yeyushengfan258/Reversal-icon-theme#86]
目前这几个图标都有，但是对flatpak版本程序都不起作用，可以添加链接 com.qq.QQ , com.qq.QQmusic , com.wps.Office.et , com.wps.Office.pdf , com.wps.Office.prometheus , com.wps.Office.wpp , com.wps.Office.wps 到对应图标吗

**Comment by neovali** [comment]
同理还有net.lutris.Lutris

**Comment by neovali** [comment]
@yeyushengfan258  对不起我搞错了，应该是com.wps.Office.kprometheus  com.wps.Office.etmain  com.wps.Office.wppmain  com.wps.Office.pdfmain  com.wps.Office.wpsmain 。
另外还有个net.lutris.Lutris 没改

**Comment by yeyushengfan258** [comment]
那这些有，没有的我再补上。
